spring:
  datasource:
   url: ${DB_URL}
   username: ${DB_USER_NAME}
   password: ${DB_PASSWORD}
   driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
         # The number of statements to group together (recommended: 10-50)
        jdbc:
          batch_size: 25
        default_batch_fetch_size: 50 
        # Groups multiple 'insert' or 'update' statements for the same table
        # to ensure they are sent in a single batch
        order_inserts: true
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    model:
      chat: ollama
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.4
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: ecommerce-knowledge-base
        initialize-schema: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 9999
