
server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: swagger-service
          uri: lb://SWAGGER-SERVICE
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html
          filters:
            - StripPrefix=0

        # 🔓 AUTH SERVICE (Public Endpoints)
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
           - Path=/api/v1/auth/*
          filters:
            - RemoveRequestHeader=Cookie
          

        # 🔓 USER REGISTER (Public)
        - id: user-service-register
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie



        # 🔐 USER SERVICE (Protected)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtValidation


        # 🔐 ORDER SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - JwtValidation

       

        - id: product-service-user
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

         # 🔐 PRODUCT SERVICE
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - JwtValidation

        # 🔐 INVENTORY SERVICE
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - JwtValidation

        # 🔐 PAYMENT SERVICE
        - id: payment-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - JwtValidation
#eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true


#jwt token
jwt:
  secret: YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2Rm  # base64 string (min 256 bits)
  access:
    expiration: 900000       # 15 minutes
  refresh:
    expiration: 604800000    # 7 days

#actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#cors properties

application:
  cors:
    allowed-origins:
      - "*"
    allowed-methods:
      - GET
      - POST
    allowed-headers:
      - Authorization
      - Content-Type
    allow-credentials: false



