spring:
  
  # MongoDB Configuration
  # data:
 mongodb:
      uri: ${M_DB}
      # If using Docker Compose networking, change localhost to 'mongodb'
  
  # Eureka Client Configuration

  
 servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # Individual file limit (e.g., one image)
      max-request-size: 50MB   # Total request limit (e.g., all images combined)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

server:
  port: 8089

# Actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always