spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/ecommerce_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
         # The number of statements to group together (recommended: 10-50)
        jdbc:
          batch_size: 25
        default_batch_fetch_size: 50 
        # Groups multiple 'insert' or 'update' statements for the same table
        # to ensure they are sent in a single batch
        order_inserts: true
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true




server:
  port: 8081


#actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#cors properties

application:
  cors:
    allowed-origins:
      - "*"
    allowed-methods:
      - GET
      - POST
    allowed-headers:
      - Authorization
      - Content-Type
    allow-credentials: false